### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by xXMcpeGamerXx03** [supercrafter333/BetterBan#1]
Mach mal mehr Commands rein und adde den Listener! :)

**Comment by xXMcpeGamerXx03** [comment]
Achja das mit Listener vergiss das einf

**Comment by supercrafter333** [comment]
Hey,
Bitte schreibe eine ausführliche bzw. Genauere Suggestion gemäß des Issue Formats dafür. Darin Listest du bitte die gewünschten Commands und was du dir unter dem Listener vorstellst auf.

MFG

**Comment by xXMcpeGamerXx03** [comment]
hund xd
