### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by SpaceMCPE** [supercrafter333/BetterBan#16]
# Bug: [Bug Name]

### Informations
BetterBan Version: [2.0.0]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [7.3.0]
PocketMine-MP Version: [3.19.0]

### Error
[Console Error:]

### readjustment instructions
[I've done...]
[1. ...]hello a player who has no pemr on the server arrives to ban someone with the interface
[2. ...]
[3. ...]

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
That's right. Thanks vor reporting, I'll fix it tomorrow.

**Comment by supercrafter333** [comment]
Fixed in V3.0.2
