### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by xXMcpeGamerXx03** [supercrafter333/BetterBan#2]
Hallo! Ich hätte ein paar Vorschläge für dein BetterBan-Plugin!

Commands:
- Es wäre schön wenn man sehen könnte wie oft ein Spieler schon gebannt worden ist! z.B. /banlog <player>
- Dann wäre ein /baninfo <player> Command noch ganz hilfreich damit man sieht, ob der jenige gebannt ist oder nicht
- Dann evtl. noch /unban obwohl das bei Pocketmine schon ist aber trzdm würde das Plugin dann nicht so leer aussehen
- Vllt noch ein /editban Befehl womit man einen Ban bearbeiten kann

Ich hoffe ich konnte dir ein paar Aufgaben geben! :)

**Comment by supercrafter333** [comment]
# Update
- [X] /banlog
- [X] /baninfo

**Comment by supercrafter333** [comment]
# Update
- [X] /editban

> In **Dev** branch

**Comment by supercrafter333** [comment]
[look at this xD](https://github.com/supercrafter333/BetterBan/commit/60e42b87474ff05b3772a9816d41f12ee58802ab)

**Comment by supercrafter333** [comment]
Done in V2.2.0!
