### ISSUE TITLE
[BUG:] Ban ip doesnt work

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/BetterBan#23]
# Bug: If you ban someone from IP (at least with the UI interface) it does not ban the player

### Informations
BetterBan Version: dev76
Server-OS: Windows10
PHP Version: 8.0.9
PocketMine-MP Version: 3.22.4
### Error
[Console Error:]
No error

**Comment by supercrafter333** [comment]
IP bans only bans an IP-Adress, not a player.

**Comment by MrBlasyMSK** [comment]
Yes, I know, but it does not kick the player from the game
