### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by ItzStarlxy** [supercrafter333/BetterBan#26]
Player can't join to server

Error log:
1. Error: "mysqli object is already closed" (EXCEPTION) in "plugins/BetterBan/src/supercrafter333/BetterBan/Permission/MySQLBanList" at line 50

2. Error: "mysqli object is already closed" (EXCEPTION) in "plugins/BetterBan/src/supercrafter333/BetterBan/Permission/MySQLBanList" at line 62

**Comment by supercrafter333** [comment]
PM3 is no logner supported.
