### ISSUE TITLE
[BUG:] Reason Duplicate

### ISSUE THREAD

**Issue by Sleak101** [supercrafter333/BetterBan#28]
When I ban someone, it says the reason twice, once under the reason tab and once under the ends by tab. I have a photo;
[Click for photo](https://imgur.com/a/DAxnH3s)

**Comment by supercrafter333** [comment]
this error is already known.

**Comment by Sleak101** [comment]
So why don't you fix it?

**Comment by supercrafter333** [comment]
I fixed it in [this commit](https://github.com/supercrafter333/BetterBan/commit/11fb0dbae7aa0ea69369e6afb1f1c3de6e4270ac).
