### ISSUE TITLE
[Suggestion:] Device ID/Client ID bans

### ISSUE THREAD

**Issue by Xd-pro** [supercrafter333/BetterBan#30]
**Is your feature request related to a problem? Please describe.**
Bans are quite easy to evade by using VPNs and alt accounts.

**Describe the solution you'd like**
Using device IDs and client IDs to ban players.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by supercrafter333** [comment]
Good suggestion. I'll add it in one of the next versions.

**Comment by supercrafter333** [comment]
ClientID's can be be changed by the user. But I can add DeviceID banning.

**Comment by Xd-pro** [comment]
> ClientID's can be be changed by the user. But I can add DeviceID banning.

They both can be changed but you can't change them on mobile devices as far as I'm aware and doing so is a fairly involved process on Windows.
