### ISSUE TITLE
[BUG:] kick-message-with-time: show {reason} at the end of the phrase

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/BetterBan#33]
# Bug: [kick-message-with-time: show {reason} at the end of the phrase]
![image](https://user-images.githubusercontent.com/85447029/158447064-1c2ea57b-13ad-4ed3-a047-1f71a896bee4.png)
```yml
kick-message-with-time: "§cBaneado por un administrador{line}§dMotivo: §7{reason}{line}§bTermina el dia: §a{time}{line}§6Apelaciones: §5discord.gg/x3a3wjsdTT"
```
### Informations
BetterBan Version: 1.4.1
Server-OS: Ubuntu
PHP Version: 8.0
PocketMine-MP Version: 4.2.3

### Error
X

### readjustment instructions
[I've done...]
[1. Ban a player with a random time (1 minute, 3 hours, whatever you prefer)]
[2. Set a random reason such as AAAAAAAA]
[3. When the player has been banned, the reason will appear at the end of the ban even if you have not put it there.]

**Comment by supercrafter333** [comment]
Thank you for report. This bug will be fixed soon.
