### ISSUE TITLE
[BUG:] Permissions not working

### ISSUE THREAD

**Issue by logannn61** [supercrafter333/BetterBan#35]
# Bug: Permissions not working

### Informations
BetterBan Version: [4.1.2]
Server-OS: [Linux]
PHP Version: [8.0.15]
PocketMine-MP Version: [4.3.1]

### Error
[Console Error:] N/A

### readjustment instructions
I set all the permissions in plugin.yml to the player and when they try a command like /ban it states that they do not have permission to use that command. I have double checked the spelling and used two different permission management plugins and it still will not work

**Comment by supercrafter333** [comment]
The permissions for banning and unbanning players are the default pocketmine-permissions.
