### ISSUE TITLE
How to add permissions to ranks?

### ISSUE THREAD

**Issue by SamOmy** [supercrafter333/BetterBan#36]
Hi,
Im new to using better ban and I was wondering how to I add permissions to ranks?
Example: betterban.command.ban
I don't know what the command would be and would appreciate if u put up a guide for that as well.

**Comment by supercrafter333** [comment]
BetterBan has nothing to do with your ranking system.

**Comment by SamOmy** [comment]
its not about my ranking system its about setting betterban permissions.
Lets say I want to give my admins permissions to use betterban. I need to go into Admin rank config and add the betterban permission but I don't know what the command would be. As of right only OP can use betterban.

**Comment by supercrafter333** [comment]
The following Commands are having the default PocketMine-MP permissions:
- Ban
- IP-Ban
- Pardon (Unban)
- Pardon-IP (Unban-IP)

**Comment by SamOmy** [comment]
yes, but how do I assign them to certain ranks?
Example: Admin rank, permissions:
- pocketmine.command.ban
- pocketmine.comman.list 
I wanna know what the command(example.command) would be in the config?

**Comment by supercrafter333** [comment]
You can't edit the permissions if you mean that.

**Comment by SamOmy** [comment]
doesn't matter I figured it out

**Comment by SamOmy** [comment]
and I did it
