### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by NJMD13** [supercrafter333/BetterBan#41]
# Bug: [Discord Webhook]

### Informations
BetterBan Version: [4.2.1]
Server-OS: [Windows]
PHP Version: [8.2.8]
PocketMine-MP Version: [5.4.3]

### Error
[Console Error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of supercrafter333\BetterBan\libs\CortexPE\DiscordWebhookAPI\Message::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://E:/Pruebas/PocketMine/plugins/BetterBan.phar/src/supercrafter333/BetterBan/libs/CortexPE/DiscordWebhookAPI/Message.php:70]

### readjustment instructions
[I've done...]
[1. Change "use-discord": from false to true]
[2. Add the link of my "discord-webhook"]
[3. Use the command "/ban SeoMC99 test 5m"]
[4. I did not send the message to the webhook, the ban was not saved and it crashed instantly
[My crashdump - Wed_Aug_23-04.34.16-UTC_2023.log](https://github.com/supercrafter333/BetterBan/files/12415188/Wed_Aug_23-04.34.16-UTC_2023.log)
]

**Comment by supercrafter333** [comment]
Will be fixed soon.
