### ISSUE TITLE
Webhook Crash

### ISSUE THREAD

**Issue by UnknownNull** [supercrafter333/BetterBan#47]
# Bug: [Bug Name]

### Informations
BetterBan Version: [4.2.1]
Server-OS: [Windows 2012 r2]
PHP Version: [8.2.0]
PocketMine-MP Version: [5.10.1]

### Error
Thread: AsyncWorker#0
Error: The script tried to call a method on an incomplete object. Please ensure that the class definition "CortexPE\DiscordWebhookAPI\Webhook" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition
File: C:/Users/Administrator/Documents/MV - RL/5.BedWars/virions/DiscordWebhookAPI-PM5/src/CortexPE/DiscordWebhookAPI/task/DiscordWebhookSendTask
Line: 68
Type: Error
Backtrace:
#0 pmsrc/src/scheduler/AsyncTask(83): CortexPE\DiscordWebhookAPI\task\DiscordWebhookSendTask->onRun()
#1 (): pocketmine\scheduler\AsyncTask->run()

**Comment by supercrafter333** [comment]
This error is caused by your BedWars plugin, not by BetterBan.

**Comment by UnknownNull** [comment]
> This error is caused by your BedWars plugin, not by BetterBan.

WTF, BedWars is just a folder!

**Comment by supercrafter333** [comment]
Why didn't you send the link of the crashdump?

**Comment by UnknownNull** [comment]
> Why didn't you send the link of the crashdump?

https://www.mediafire.com/file/vytw9j79kbzf7ji/Mon_Jan_29-08.46.15-UTC_2024.log/file

**Comment by supercrafter333** [comment]
Please send the link from https://crash.pmmp.io
