### ISSUE TITLE
#Bug: Reason Loop

### ISSUE THREAD

**Issue by ZenZoya-coder** [supercrafter333/BetterBan#5]
# Bug: Reason Loop

### Informations
BetterBan Version: [1.0.1]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.2]
PocketMine-MP Version: [3.17.5]

### Bug Info
Ban reason is looping at the end of ban info

**Comment by ZenZoya-coder** [comment]
# Bug: Reason Loop
### Informations
BetterBan Version: [1.0.1]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.2]
PocketMine-MP Version: [3.17.5]

### Bug Info
Ban reason is looping at the end of ban info

**Comment by supercrafter333** [comment]
Pocketmine does Not Support PHP ^8.

**Comment by supercrafter333** [comment]
Please Open a valid bug-report issue

**Comment by supercrafter333** [comment]
Please Open a new Issue with more informations
