### ISSUE TITLE
[Suggestion:] Implement reporting system on Discord/Twitter

### ISSUE THREAD

**Issue by UnEnanoMas** [supercrafter333/BetterBan#6]
I would like to know if it is possible for you to add that when a player is banned, that you can put the api of a bot in discord or the twitter account, so that it publishes the message of "the player has been banned for x, x days "

Like this

https://www.youtube.com/watch?v=b7gt3HsbBv4

**Comment by supercrafter333** [comment]
Good Idea. I'll add Discord Webhook Support.

**Comment by supercrafter333** [comment]
Done in V2.1.0!
